# Read the documentation https://github.com/Orbitale/EasyImpressBundle#yml-reference for more details about yaml options
data:
    # In seconds
    transition-duration: 1000

slides:
    -
        content: 'Hello world!'
        data:
            x: 0
            y: 0
            z: 1000
            rotate-x: 0
            rotate-y: 0
            rotate-z: 0
