# Read the documentation: https://symfony.com/doc/master/cmf/bundles/seo/configuration.html
cmf_seo:
    persistence:
        phpcr: ~
    title: '%%content_title%% | Insert your base Title'
    description: 'Insert you base description here. %%content_description%%'
