# Read the documentation: http://symfony.com/doc/master/cmf/bundles/seo/configuration.html
cmf_seo:
#    persistence:
#        phpcr:
#            enabled: true
#    title: %%content_title%% | Symfony2 CMF
#    description: The Symfony2 Content Management Framework. %%content_description%%
#    sitemap:
#        enabled: true
#        defaults:
#            default_change_frequency: always
#            templates:
#                html: :sitemap/index.html.twig
#                xml: ::sitemap:index.xml.twig
#            loaders:
#                - _all
#            guessers:
#                - _all
#            voters:
#                - _all
#        configurations:
#            sitemap: ~
#    error:
#        exclusion_rules:
#            - { path: ^/admin }
#    alternate_locale:
#        enabled: true
#        provider_id: app.alternate_locale.provider
