lexik_jose:
    ttl: 1000
    server_name: '%env(SL_JOSE_BRIDGE_SERVER_NAME)%'
    key_set: '%env(SL_JOSE_BRIDGE_SIGNATURE_KEYSET)%'
    key_index: 0
    signature_algorithm: 'HS512'
    encryption:
        enabled: true
        key_set: '%env(SL_JOSE_BRIDGE_ENCRYPTION_KEYSET)%'
        key_index: 0
        key_encryption_algorithm: 'A256GCMKW'
        content_encryption_algorithm: 'A256GCM'
