# Basic configuration for AWS SDK
# Please visit http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html
# for more information

aws:
    version: latest
    region: us-east-1
    credentials:
        key: "%env(AWS_CREDENTIAL_KEY)%"
        secret: "%env(AWS_CREDENTIAL_SECRET)%"
